### ISSUE TITLE
Add gopack tag for building packages

### ISSUE THREAD

**Issue by gongled** [essentialkaos/rpmbuilder#13]
You have a great tool for packaging go application which called `gopack`. What do you think about support `gopack` tag to create archive automatically?

**Comment by andyone** [comment]
This looks like a nice idea. I'll implement this feature in next release.

**Comment by andyone** [comment]
gopack support added in #25 (https://github.com/essentialkaos/rpmbuilder/pull/25/commits/0f44f95a3a36a67e32ef40e4aff429ab9cba46ce)

**Comment by andyone** [comment]
Version 1.4.0 with this feature is released today.
