### ISSUE TITLE
Add integration with perfecto utility

### ISSUE THREAD

**Issue by gongled** [essentialkaos/rpmbuilder#56]
Hello,

I know that RPMBuilder uses `rpmlint` to perform strict and pedantic checks for spec file. it works fine and helps me build package in one-line command. Few weeks ago you have been released first public version of `perfecto` utility which makes validation much better for usage. So then, I thought, that would be nice if `RPMBuilder` includes one another type of checking in addition to `strict` and `pedantic` options.

**Comment by andyone** [comment]
Hi! I made perfecto with a focus on using in rpmbuilder. So I will try to add integration with perfecto in near feature.

**Comment by andyone** [comment]
Today I have released [rpmbuilder 2.2.0](https://github.com/essentialkaos/rpmbuilder/releases/tag/v2.2.0) with perfecto support. I hope you will enjoy this feature. 😉

**Comment by gongled** [comment]
Thank you. I have finished testing it a few moments ago. It works _perfectly_!
