### ISSUE TITLE
CentOR/RHEL 8 support?

### ISSUE THREAD

**Issue by hunter-nl** [essentialkaos/rpmbuilder#75]
It would be nice if CentOS/RHEL 8 is going to be supported.

**Comment by andyone** [comment]
Hi!
`rpmbuilder` is fully compatible with RHEL8/CentOS8. Which features don't work on these systems?

**Comment by hunter-nl** [comment]
centos8.docker file is missing, It seems pinentry package is required to sign the rpm package.

**Comment by andyone** [comment]
Closed by #114
