### ISSUE TITLE
Use yum-builddep to fetch dependencies from spec

### ISSUE THREAD

**Issue by gongled** [essentialkaos/rpmbuilder#8]
Would be great to use `yum-builddep` from `yum-utils` to resolve dependencies instead of manual parsing spec files. I've prepared prototype and It works fine, but I suppose that your implementation will be better than mine.

**Comment by andyone** [comment]
Hi! Thanks for nice idea. `yum-builddep` usage implemented in #9. Can you test and compare with your prototype? I will be much appreciated for any feedback.

Be aware, if want to test devel version with terrafarm, you should update `rpmbuilder-node` package to `1.0.1` on all your nodes.

**Comment by gongled** [comment]
I've built the package from 'develop' branch. Well, it works nice. Thanks!

**Comment by andyone** [comment]
Glad to hear that.
